controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


    antenna_forward_position_controller:
      type: forward_command_controller/ForwardCommandController


    forward_torque_controller:
      type: forward_command_controller/ForwardCommandController


    pid_controller:
      type: pid_command_controller/PIDCommandController

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: false



antenna_forward_position_controller:
  ros__parameters:
    joints:
      - l_antenna
      - r_antenna
    interface_name: position
    use_sim_time: false

forward_torque_controller:
  ros__parameters:
    joints:
      - l_antenna
      - r_antenna
    interface_name: torque
    use_sim_time: false


pid_controller:
  ros__parameters:
    joints:

      - l_antenna
      - r_antenna
    use_sim_time: false


